### ISSUE TITLE
Application start issue

### ISSUE THREAD

**Issue by Jikol** [Pikl/ArcDps-Butler#1]
Do you need something special libraries to start the program? Becouse it doesn't work at my desktop. If I start it on my laptop, it works fine, but unfortunatelly on setting area i can't move content due to missing sliding bar. So, do I need something additional for Discord push excepts Bot Token and Channel ID?

**Comment by Pikl** [comment]
All you should need is .NET Framework 4.6.1.
Bot Token and Channel ID is everything, although of course you'll need to set up the bot user account and invite it to your server. [See here for an example post](https://i.imgur.com/vl5VOaH.png)

I'm not quite sure what you mean about the setting area's missing scrollbar? Could you elaborate?

Note that if there is interest, I have some half finished updates for the Discord bot and posting functionality - I could finish them off if someone is actually interested in this thing.
